server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: github
  web:
    cors:
      allowed-origins: http://localhost:5173

events:
  filter:
    exclude-bot-events: false

github:
  api:
    base-url: https://api.github.com
    events-path: /events
    token: ${GITHUB_TOKEN:}
    per-page: 100
    min-poll-interval-seconds: 60
    polling-enabled: true
    gradual-release-enabled: true
    release-window-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info
